In [8]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
path2csv = './csv/'
params = ['threshold-val', 'percent-grammar-1']

In [10]:
def csv_to_df(path2csv):
    dff_all_from_csv = []
    print(path2csv)
    
    for root, dirs, files in os.walk(path2csv):
        print(root, files)
        for file in files:
            if not file.endswith('.csv'):
                continue
            df = pd.read_csv(os.path.join(root, file), skiprows=range(0,6))
            df.set_index(['[run number]', '[step]'], inplace=True)
            dff_all_from_csv.append(df)
    return dff_all_from_csv

In [11]:
dff_all_from_csv = csv_to_df(path2csv)

./csv/
./csv/ ['Language Change_converge_stop experiment1-individual-perc-table.csv', 'Language Change_converge_stop experiment3-threshold-perc-table.csv', 'Language Change_converge_stop experiment2-threshold-perc-thres-table.csv', 'Language Change_converge_stop experiment4-reward-perc-table.csv', 'Language Change_converge_stop experiment6-threshold-sink-state-table.csv', 'Language Change_converge_stop experiment5-threshold-thres-table.csv']


In [12]:
def t_test(vals1, vals2):
    _, p_val = stats.ttest_ind(vals1, vals2)
    if p_val < 0.05:
        print("p-value is significant: ", p_val)
    else:
        print("p-value is not significant: ", p_val)

In [13]:
# statistical relevance: t-test
from scipy import stats

for experiment_df in dff_all_from_csv:
    p = 'percent-grammar-1' 
    vals2test = [10, 60, 90]
    steps_p = {}
    for val in vals2test:
        temp_df = experiment_df.reset_index(inplace=False).groupby([p, "[run number]"]).max()["[step]"].reset_index(inplace=False)
        steps_p[val] = temp_df[temp_df[p] == val]['[step]'].values

    print(steps_p[10])
    # thresholds p 0.1 vs 0.9
    t_test(steps_p[10], steps_p[90])

    # thresholds p 0.1 vs 0.6
    t_test(steps_p[10], steps_p[60])

    # thresholds p 0.6 vs 0.9
    t_test(steps_p[60], steps_p[90])

[122   4   9   1  62   6  39   4   6   0]
p-value is not significant:  0.5433757442546482
p-value is not significant:  0.19435375116462922
p-value is not significant:  0.49920000740435133
[200 200 200 200 200 200 200 200 200 200]
p-value is significant:  2.534407016713576e-47
p-value is significant:  1.0858618753364026e-45
p-value is significant:  2.130126127468593e-05
[  3   3   3   2   4   4   4   3   3   5   3 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200]
p-value is significant:  3.7158435786910234e-27
p-value is significant:  6.164809956869085e-08
p-value is significant:  1.3305825081510619e-06


/Users/klara/Developer/Uni/SoSe24/I2ABM/edu_introabm_exercise/I2ABM_env/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py:531: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)


[165164 163195 162615 165485 131649 158571 157888 162652 158502]
p-value is not significant:  nan
p-value is not significant:  nan
p-value is not significant:  nan
[]
p-value is not significant:  nan
p-value is not significant:  nan
p-value is not significant:  nan
[]
p-value is not significant:  nan
p-value is not significant:  nan
p-value is not significant:  nan


Language Change_converge_stop experiment1-individual-perc-table.csv: percent-grammar-1 is significant for the time it takes until convergence